FROM eclipse-temurin:11-alpine
COPY target/server_start.jar /server_start.jar
# This is the port that your javalin application will listen on
EXPOSE 7000 
ENTRYPOINT ["java", "-jar", "/server_start.jar"]